FROM rust:latest as builder

# Install the Windows target
RUN rustup target add x86_64-pc-windows-msvc

# Set the working directory
WORKDIR /usr/src/app

# Copy the source code
COPY . .

# Build the project for Windows
RUN cargo build --release --target x86_64-pc-windows-msvc

FROM scratch
COPY --from=builder /usr/src/app/target/x86_64-pc-windows-msvc/release/RustGetSystemInfo.exe .